[package]
name = "extended"
version = "0.2.0"
edition = "2021"
authors = ["Dietrich Epp <code-author@moria.us>"]
readme = "README.md"
repository = "https://github.com/depp/extended-rs"
homepage = "https://github.com/depp/extended-rs"
license = "MIT"
description = """
Extended precision 80-bit floating-point numbers (f80).
"""
keywords = ["float"]
categories = ["mathematics"]
